// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0EXFvUgtL4MqrVl69Ef50RrszKPp0yk',
    appId: '1:519697405267:android:462cd77bb9556f8d9dbda6',
    messagingSenderId: '519697405267',
    projectId: 'echostream-4a3ad',
    storageBucket: 'echostream-4a3ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_V49LXedEtk5axch2gTDXCBtPqW77tO0',
    appId: '1:519697405267:ios:15dae07860b1a6089dbda6',
    messagingSenderId: '519697405267',
    projectId: 'echostream-4a3ad',
    storageBucket: 'echostream-4a3ad.firebasestorage.app',
    androidClientId: '519697405267-jl7uu1hsg7nluonskrkhsd8jgl25mnh8.apps.googleusercontent.com',
    iosClientId: '519697405267-cud0mc0imnp2m6o73dfma84kv3popjhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.echoStream',
  );

}